### ISSUE TITLE
Skip sunpy.map for faster loading of data from FITS files

### ISSUE THREAD

**Issue by wtbarnes** [mnicely/dali_examples#1]
I noticed that the data from the FITS files is being loaded via `sunpy.map.Map`. For these cases, this is probably adding quite a bit of unnecessary overhead. `Map` provides a lot of conveniences for users, but does *a lot* of stuff behind the scenes to make loading these files as painless possible.

For just getting at the raw data arrays as quick as possible, I'd recommend using `astropy.io.fits` directly (this is what sunpy is doing underneath the hood, just with a lot of syntactic sugar on top),

```python
from astropy.io import fits
with fits.open(my_fits_filename) as hdul:
    hdul[1].verify('silentfix+warn')  # oftentimes the headers are broken; fix them or astropy will complain
    data = hdul[1].data
```

In these examples, this would replace the `sunpy.map.Map(f)` call in `__next__`.

**Comment by mnicely** [comment]
@wtbarnes Thanks for the additional information. I have applied your suggested changes!
